// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.17.1
// source: thompsonsampling.proto

package thompsonsampling

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Desc              bool     `protobuf:"varint,1,opt,name=desc,proto3" json:"desc,omitempty"`                                                   //是否倒叙从大到小
	BusinessNamespcae string   `protobuf:"bytes,2,opt,name=business_namespcae,json=businessNamespcae,proto3" json:"business_namespcae,omitempty"` //针对业务控制的命名空间,空字符串含义为全局,redis中以`__global__`替代
	TargetNamespace   string   `protobuf:"bytes,3,opt,name=target_namespace,json=targetNamespace,proto3" json:"target_namespace,omitempty"`       //针对目标控制的命名空间,指代用户,用户分群等逻辑概念,空字符串含义为全局,redis中以`__global__`替代
	Candidates        []string `protobuf:"bytes,4,rep,name=candidates,proto3" json:"candidates,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thompsonsampling_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_thompsonsampling_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_thompsonsampling_proto_rawDescGZIP(), []int{0}
}

func (x *Query) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

func (x *Query) GetBusinessNamespcae() string {
	if x != nil {
		return x.BusinessNamespcae
	}
	return ""
}

func (x *Query) GetTargetNamespace() string {
	if x != nil {
		return x.TargetNamespace
	}
	return ""
}

func (x *Query) GetCandidates() []string {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderedCandidates []string `protobuf:"bytes,1,rep,name=ordered_candidates,json=orderedCandidates,proto3" json:"ordered_candidates,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thompsonsampling_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_thompsonsampling_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_thompsonsampling_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetOrderedCandidates() []string {
	if x != nil {
		return x.OrderedCandidates
	}
	return nil
}

var File_thompsonsampling_proto protoreflect.FileDescriptor

var file_thompsonsampling_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x68, 0x6f, 0x6d, 0x70, 0x73, 0x6f, 0x6e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x74, 0x68, 0x6f, 0x6d, 0x70, 0x73,
	0x6f, 0x6e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72,
	0x65, 0x22, 0x95, 0x01, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12,
	0x2d, 0x0a, 0x12, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x63, 0x61, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x62, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x63, 0x61, 0x65, 0x12, 0x29,
	0x0a, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64,
	0x5f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x11, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x64, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x32, 0x5f, 0x0a, 0x10, 0x54, 0x48, 0x4f, 0x4d, 0x50, 0x53, 0x4f, 0x4e,
	0x53, 0x41, 0x4d, 0x50, 0x4c, 0x49, 0x4e, 0x47, 0x12, 0x4b, 0x0a, 0x04, 0x52, 0x61, 0x6e, 0x6b,
	0x12, 0x1e, 0x2e, 0x74, 0x68, 0x6f, 0x6d, 0x70, 0x73, 0x6f, 0x6e, 0x73, 0x61, 0x6d, 0x70, 0x6c,
	0x69, 0x6e, 0x67, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x1a, 0x21, 0x2e, 0x74, 0x68, 0x6f, 0x6d, 0x70, 0x73, 0x6f, 0x6e, 0x73, 0x61, 0x6d, 0x70, 0x6c,
	0x69, 0x6e, 0x67, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x2e, 0x2f, 0x74, 0x68, 0x6f, 0x6d, 0x70,
	0x73, 0x6f, 0x6e, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x64, 0x65, 0x63, 0x6c, 0x61,
	0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_thompsonsampling_proto_rawDescOnce sync.Once
	file_thompsonsampling_proto_rawDescData = file_thompsonsampling_proto_rawDesc
)

func file_thompsonsampling_proto_rawDescGZIP() []byte {
	file_thompsonsampling_proto_rawDescOnce.Do(func() {
		file_thompsonsampling_proto_rawDescData = protoimpl.X.CompressGZIP(file_thompsonsampling_proto_rawDescData)
	})
	return file_thompsonsampling_proto_rawDescData
}

var file_thompsonsampling_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_thompsonsampling_proto_goTypes = []interface{}{
	(*Query)(nil),    // 0: thompsonsamplingdeclare.Query
	(*Response)(nil), // 1: thompsonsamplingdeclare.Response
}
var file_thompsonsampling_proto_depIdxs = []int32{
	0, // 0: thompsonsamplingdeclare.THOMPSONSAMPLING.Rank:input_type -> thompsonsamplingdeclare.Query
	1, // 1: thompsonsamplingdeclare.THOMPSONSAMPLING.Rank:output_type -> thompsonsamplingdeclare.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_thompsonsampling_proto_init() }
func file_thompsonsampling_proto_init() {
	if File_thompsonsampling_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_thompsonsampling_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thompsonsampling_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_thompsonsampling_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thompsonsampling_proto_goTypes,
		DependencyIndexes: file_thompsonsampling_proto_depIdxs,
		MessageInfos:      file_thompsonsampling_proto_msgTypes,
	}.Build()
	File_thompsonsampling_proto = out.File
	file_thompsonsampling_proto_rawDesc = nil
	file_thompsonsampling_proto_goTypes = nil
	file_thompsonsampling_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// THOMPSONSAMPLINGClient is the client API for THOMPSONSAMPLING service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type THOMPSONSAMPLINGClient interface {
	Rank(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Response, error)
}

type tHOMPSONSAMPLINGClient struct {
	cc grpc.ClientConnInterface
}

func NewTHOMPSONSAMPLINGClient(cc grpc.ClientConnInterface) THOMPSONSAMPLINGClient {
	return &tHOMPSONSAMPLINGClient{cc}
}

func (c *tHOMPSONSAMPLINGClient) Rank(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/thompsonsamplingdeclare.THOMPSONSAMPLING/Rank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// THOMPSONSAMPLINGServer is the server API for THOMPSONSAMPLING service.
type THOMPSONSAMPLINGServer interface {
	Rank(context.Context, *Query) (*Response, error)
}

// UnimplementedTHOMPSONSAMPLINGServer can be embedded to have forward compatible implementations.
type UnimplementedTHOMPSONSAMPLINGServer struct {
}

func (*UnimplementedTHOMPSONSAMPLINGServer) Rank(context.Context, *Query) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rank not implemented")
}

func RegisterTHOMPSONSAMPLINGServer(s *grpc.Server, srv THOMPSONSAMPLINGServer) {
	s.RegisterService(&_THOMPSONSAMPLING_serviceDesc, srv)
}

func _THOMPSONSAMPLING_Rank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(THOMPSONSAMPLINGServer).Rank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thompsonsamplingdeclare.THOMPSONSAMPLING/Rank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(THOMPSONSAMPLINGServer).Rank(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

var _THOMPSONSAMPLING_serviceDesc = grpc.ServiceDesc{
	ServiceName: "thompsonsamplingdeclare.THOMPSONSAMPLING",
	HandlerType: (*THOMPSONSAMPLINGServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rank",
			Handler:    _THOMPSONSAMPLING_Rank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thompsonsampling.proto",
}
